# Generated by Django 5.0 on 2023-12-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_coursevideo_secion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursevideo',
            old_name='secion',
            new_name='section',
        ),
    ]
