# Generated by Django 5.0 on 2023-12-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_secion_coursevideo_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortvideo',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
